const constants = {
    MAX_EMAIL_LENGTH: 254,
    MAX_URL_LENGTH: 2048,
    MAX_USER_FULL_NAME_LENGTH: 128, 
    MAX_USER_NAME_LENGTH: 64,
    MAX_HOUSEHOLD_NAME_LENGTH: 100,
    MAX_STREET_ADDRESS_LENGTH: 100,
    MAX_COUNTRY_LENGTH: 90,
    MAX_CITY_LENGTH: 45,
    MAX_STATE_LENGTH: 64,
    MAX_POSTAL_CODE_LENGTH: 5,
}

export default constants

